### ISSUE TITLE
I am facing problem while using the library in React/typescript app I also run the npm command but problem is still there

### ISSUE THREAD

**Issue by AHMADanis** [wingkwong/react-quiz-component#75]
Could not find a declaration file for module 'react-quiz-component'. '/Users/anees/Documents/coding/eu_drive_fe/node_modules/react-quiz-component/lib/Quiz.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-quiz-component` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-quiz-component';`

**Comment by sajumani** [comment]
Am also facing issue with TypeScript

**Comment by wingkwong** [comment]
Please try on 0.5.0

**Comment by wingkwong** [comment]
fixed in 0.5.1

**Comment by 127** [comment]
Looks like it's not fixed or broken back in 0.7.1
same error reproduces

```
Could not find a declaration file for module 'react-quiz-component'. '/Users/user/dev/lt/proj/node_modules/react-quiz-component/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-quiz-component` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-quiz-component';`ts(7016)
```
